### ISSUE TITLE
WCSPH Visualization Error

### ISSUE THREAD

**Issue by 199ChenNuo** [g1n0st/GAMES201#1]
I'm sorry that I left Chinese messages before and didn't notice that I commented line 227 in wcsph.py.
```
# block2.deactivate_all()
```

If I uncomment line 227, taichi will report a RuntimeError:
```
Traceback (most recent call last):
  File "wcsph.py", line 294, in <module>
    substep()
  File "wcsph.py", line 235, in substep
    update_neighbors()
  File "wcsph.py", line 227, in update_neighbors
    block2.deactivate_all()
  File "/home/.local/lib/python3.6/site-packages/taichi/lang/snode.py", line 162, in deactivate_all
    c.deactivate_all()
  File "/home/.local/lib/python3.6/site-packages/taichi/lang/snode.py", line 166, in deactivate_all
    meta.snode_deactivate(self)
  File "/home/.local/lib/python3.6/site-packages/taichi/lang/kernel_impl.py", line 629, in wrapped
    return primal(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/taichi/lang/kernel_impl.py", line 557, in __call__
    return self.compiled_functions[key](*args)
  File "/home/.local/lib/python3.6/site-packages/taichi/lang/kernel_impl.py", line 515, in func__
    t_kernel(launch_ctx)
RuntimeError: [type_check.cpp:visit@141] [$2011] S19 has 1 indices. Indexed with 2.
```

And if I left line 227 commented, the rendering result will be like the image captured below.
![image](https://user-images.githubusercontent.com/25026408/121488154-64387180-ca05-11eb-8748-bf4788629f27.png)

Thank you~

**Comment by g1n0st** [comment]
Sorry for replying so late, thanks for you report this issue:

(1) For Runtime Error on `block2.deactivate_all()`

When I wrote this sph solver, this version of Taichi(0.6.4) is earlier than now(0.7.21), I cannot figure out whether my code is wrong in syntax(https://github.com/g1n0st/GAMES201/blob/12cf798d4dd9cd69ce06dea8a0fd32700420edec/extra/WeaklyCompressibleSPH/wcsph.py#L63-L66), or it's a potential bug in the later version. I've already reported this issue to the Taichi Community.

(2) For Visualization Error

I'm sorry that I could not reproduce this error in `CPU` backend, and my laptop not supports `ti.cuda`. Could you try to switch backend to `ti.cpu` and see whether the result is same as `ti.gpu`?

**Comment by 199ChenNuo** [comment]
Thank you for replying!

I tried `ti.cpu` and it worked!
![000000](https://user-images.githubusercontent.com/25026408/121771773-1148f080-cba4-11eb-8424-183acecbb29c.png)
 
![000024](https://user-images.githubusercontent.com/25026408/121771839-81577680-cba4-11eb-9f79-41d5347894ba.png)

Although there are some confusing holes, the visual results are quite good! I think these holes may be related to taichi. Thank you for reporting to the Taichi Community by the way.
