### ISSUE TITLE
swmpm3d中固液粒子碰撞问题

### ISSUE THREAD

**Issue by youeryuan1** [g1n0st/GAMES201#2]
大佬您好！
  我试着跑了您的swmpm3d程序，但是其中的固体和液体粒子不能相互碰撞，希望您能解答。万分感谢！

**Comment by g1n0st** [comment]
抱歉回复晚了：
因为按照蒋老师17年的paper 《Multi-species simulation of porous sand and water mixtures》，水和沙子有各自的背景网格，它们之间的耦合只有particle to grid以后，在背景网格上进行动量交换，粒子和粒子之间确实是会碰撞甚至穿透的，但是这应该也满足多孔材质的性质

**Comment by youeryuan1** [comment]
十分感谢您的回复！
在您的swmpm2d这一程序中，P2G和G2P之间有动量交换的部分，并且在SWMPM3D中也有相关三维化的动量交换。让我疑惑的是，2D程序中固液粒子碰撞和现实情况非常相符，但是3D程序中就不再碰撞了，难道在三维空间中动量交换会失效吗? 希望您能解答。

**Comment by g1n0st** [comment]
嗯嗯，我当时主要跑的demo都是2d的case，3D的只是实现了但是没有仔细测试过，这个可能确实是哪里有bug～

**Comment by youeryuan1** [comment]
好嘞，十分感谢！这个问题想了好多天了，感谢您的答复！

**Comment by g1n0st** [comment]
3D最终效果以蒋老师paper为准～ 我这个只是个人的实现而已hhhh

**Comment by youeryuan1** [comment]
哈哈哈哈哈哈哈，太强了大佬

**Comment by youeryuan1** [comment]
大佬，又来打扰您了！
最近研读了很多论文里的应力张量公式，一直不能理解在P2G过程中以下两行代码对应的公式在哪里。	        
stress = U @ (2 * mu_s * inv_sig @ e + lambda_s * e.trace() * inv_sig) @ V.transpose() ；
stress = (-p_vol * 4 * inv_dx * inv_dx) * stress @ F_s[p].transpose() 
让我感到疑惑的是为什么要用(-p_vol * 4 * inv_dx * inv_dx) 来乘stress，很想知道它的实际意义。 
盼望您的答复！万分感谢！

**Comment by g1n0st** [comment]
GAMES Lecture 9, 0:20:48 里面有这个公式详细的讲解哈
https://www.bilibili.com/video/BV1ZK411H7Hc/?p=8&vd_source=e9885f9d4a081a0e037cf90a03cd5920&t=1248.2

**Comment by youeryuan1** [comment]
谢谢大佬！真的太感谢您啦！😊😊
